# Generated by Django 2.1.5 on 2019-10-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_view',
            field=models.IntegerField(default=0),
        ),
    ]
